site_name: Prefeitura de Una√≠
theme:
  name: material
  language: "pt"

nav:
  - Home: index.md
  - Cronograma: cronograma.md
  - Planejamento:
    - Sites Avaliados: planejamento/sites.md
    - Site Escolhido: planejamento/site.md
  - Processo de Design: processo.md